spree:
  image: spreecommerce/spree:3.6.4
  ports: 
    - "3000:3000"

web:
  build: .
  command: python cargaspree.py
  ports:
    - "5000:5000"
  volumes:
    - .:/carga
  links:
    - db
    - spree
db:
  image: mongo
  volumes:
    - .:/carga

 
  